### Recuperar todas las peliculas
GET https://programacionwebii-production.up.railway.app/movies
### Recuperar una pelicula por id
GET https://programacionwebii-production.up.railway.app/movies/21
### Recuperar todas las peliculas por un genero
GET https://programacionwebii-production.up.railway.app/movies?genre=drama
### Crear una pelicula
POST https://programacionwebii-production.up.railway.app/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": "drama",
    "rate": 9.2
}
###Actualizar una pelicula
PATCH https://programacionwebii-production.up.railway.app/movies/2
Content-Type: application/json

{
    "year": 2010
}
###Eliminar una pelicula
DELETE https://programacionwebii-production.up.railway.app/movies/21