### Recuperar todas las reviews
GET https://programacionwebii-production.up.railway.app/reviews

### Recuperar una review por id
GET https://programacionwebii-production.up.railway.app/reviews/41

### Recuperar todas las reviews de una pelicula
GET https://programacionwebii-production.up.railway.app/reviews/movie/1

### Recuperar todas las reviews de un usuario
GET https://programacionwebii-production.up.railway.app/reviews/user/1

### Crear una review
POST https://programacionwebii-production.up.railway.app/reviews
Content-Type: application/json

{
    "movieId": 1,
    "userId": 1,
    "rating": 4.5,
    "comment": "Great movie!"
}

### Actualizar una review
PATCH https://programacionwebii-production.up.railway.app/reviews/41
Content-Type: application/json

{
    "rating": 3.5
}

### Eliminar una review
DELETE https://programacionwebii-production.up.railway.app/reviews/41