### Recuperar todos los usuarios
GET https://programacionwebii-production.up.railway.app/users
### Recuperar un usuario por id
GET https://programacionwebii-production.up.railway.app/users/23
### Crear un usuario
POST https://programacionwebii-production.up.railway.app/users
Content-Type: application/json

{
    "username": "juantomasm0",
    "email": "juantomasm0@gmail.com",
    "password": "juanps17",
}
###Actualizar una pelicula
PATCH https://programacionwebii-production.up.railway.app/users/23
Content-Type: application/json

{
    "role": "admin"
}
###Eliminar un usuario
DELETE https://programacionwebii-production.up.railway.app/users/23
###Realizar login
POST https://programacionwebii-production.up.railway.app/users/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "password2"
}

###Logout, se debe borrar la cookie con el token
POST https://programacionwebii-production.up.railway.app/users/logout