### Recuperar todos los usuarios
GET http://localhost:3000/users
### Recuperar un usuario por id
GET http://localhost:3000/users/23
### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "juantomasm0",
    "email": "juantomasm0@gmail.com",
    "password": "juanps17"
}
###Actualizar una pelicula
PATCH http://localhost:3000/users/23
Content-Type: application/json

{
    "username": "modifiedName"
}
###Eliminar un usuario
DELETE http://localhost:3000/users/23
###Realizar login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "juantomasm0@gmail.com",
    "password": "juanps17"
}

###Logout, se debe borrar la cookie con el token
POST http://localhost:3000/users/logout