### Recuperar todos los usuarios
GET http://localhost:3000/users
### Recuperar un usuario por id
GET http://localhost:3000/users/4
### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "juantomasm0",
    "email": "juantomasm0@gmail.com",
    "password": "juanps17",
}
###Actualizar una pelicula
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
    "username": "modifiedName"
}
###Eliminar una pelicula
DELETE http://localhost:3000/users/2